{
 "title": "test",
 "time": { "from": "2025-12-20T13:38:24.000Z", "to": "2025-12-20T13:49:51.000Z" },
 "panels": [
  {
   "title": "Доля высокорисковых предсказаний",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(high_risk_predictions_total[5m]) / rate(model_predictions_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Ошибки (4xx/5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status_code=~\"[45]..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Распределение предсказаний модели",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(ml_prediction_values_bucket[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время отклика (95-й перцентиль)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Частота запросов (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}